#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

REPO="spoo-me/spoo-android"
GH_ENV="release"

# The release workflow reads its secrets from the "release" environment, so
# these go there rather than to the repo scope.
set_env_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" --repo "$REPO" --env "$GH_ENV" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s %s in the %s environment\n' "$GREEN" "$RESET" "$name" "$GH_ENV"
      return
    fi
  fi
  SKIPPED+=("$name (gh secret set $name --repo $REPO --env $GH_ENV)")
  warn "could not set $name; do it by hand later"
}

banner "spoo for Android: release signing"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "What you are about to create"
say "Releases are built and signed by CI. For that it needs an upload key,"
say "which this wizard creates once and stores as GitHub secrets."
printf '\n'
printf '  %s%sThis key becomes the permanent identity of the app.%s\n' "$BOLD" "$YELLOW" "$RESET"
say "Every future update must be signed with it. Lose it and you cannot ship"
say "an update to anyone who already installed the app: they would have to"
say "uninstall and reinstall from scratch. Back it up before you finish."
printf '\n'
for tool in keytool gh; do
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %s found\n' "$GREEN" "$RESET" "$tool"
  else
    printf '  %s✗%s %s missing: install it first\n' "$RED" "$RESET" "$tool"
    exit 1
  fi
done
gh auth status >/dev/null 2>&1 || { printf '  %s✗%s gh is not logged in: run gh auth login\n' "$RED" "$RESET"; exit 1; }
printf '  %s✓%s gh is authenticated\n' "$GREEN" "$RESET"
confirm "Create the signing key now?" || exit 0

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the keystore"
say "Keep this file outside the repo so it can never be committed."
ask KEYSTORE_PATH "Where should it live? [$HOME/.spoo/upload-key.jks]"
KEYSTORE_PATH="${KEYSTORE_PATH:-$HOME/.spoo/upload-key.jks}"
ask KEY_ALIAS "Key alias: [upload]"
KEY_ALIAS="${KEY_ALIAS:-upload}"

if [[ -f "$KEYSTORE_PATH" ]]; then
  say ""
  note "a keystore already exists at $KEYSTORE_PATH; reusing it"
  ask_secret KEYSTORE_PASSWORD "Its store password:"
  ask_secret KEY_PASSWORD "Its key password (Enter if same as store):"
  KEY_PASSWORD="${KEY_PASSWORD:-$KEYSTORE_PASSWORD}"
else
  ask_secret KEYSTORE_PASSWORD "Choose a store password:"
  [[ -n "$KEYSTORE_PASSWORD" ]] || { printf '  %s✗%s a password is required\n' "$RED" "$RESET"; exit 1; }
  ask_secret KEY_PASSWORD "Choose a key password (Enter to reuse the store one):"
  KEY_PASSWORD="${KEY_PASSWORD:-$KEYSTORE_PASSWORD}"
  mkdir -p "$(dirname "$KEYSTORE_PATH")"
  # 30 years: Play rejects keys that expire before 2033.
  keytool -genkeypair \
    -keystore "$KEYSTORE_PATH" \
    -alias "$KEY_ALIAS" \
    -keyalg RSA -keysize 4096 -validity 10950 \
    -storepass "$KEYSTORE_PASSWORD" -keypass "$KEY_PASSWORD" \
    -dname "CN=spoo.me, O=spoo.me, OU=spoo-android, C=IN" >/dev/null 2>&1
  chmod 600 "$KEYSTORE_PATH"
  printf '  %s✓%s created %s\n' "$GREEN" "$RESET" "$KEYSTORE_PATH"
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Check the key actually opens"
say "A wrong password here would only surface as a failed release later."
if keytool -list -keystore "$KEYSTORE_PATH" -alias "$KEY_ALIAS" \
     -storepass "$KEYSTORE_PASSWORD" >/dev/null 2>&1; then
  printf '  %s✓%s alias "%s" opens with that password\n' "$GREEN" "$RESET" "$KEY_ALIAS"
  say ""
  say "Fingerprint (the same one Play will show you later):"
  keytool -list -v -keystore "$KEYSTORE_PATH" -alias "$KEY_ALIAS" \
    -storepass "$KEYSTORE_PASSWORD" 2>/dev/null | grep -E "SHA256:" | head -1 | sed 's/^/    /'
else
  printf '  %s✗%s could not open the keystore with those values\n' "$RED" "$RESET"
  exit 1
fi
pause "Looks right?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Hand the key to CI"
say "Creating the \"$GH_ENV\" environment on $REPO, then storing four secrets."
gh api -X PUT "repos/$REPO/environments/$GH_ENV" --silent >/dev/null 2>&1 \
  && printf '  %s✓%s environment ready\n' "$GREEN" "$RESET" \
  || warn "could not create the environment; secrets may fail below"
set_env_secret KEYSTORE_BASE64 "$(base64 < "$KEYSTORE_PATH" | tr -d '\n')"
set_env_secret KEYSTORE_PASSWORD "$KEYSTORE_PASSWORD"
set_env_secret KEY_ALIAS "$KEY_ALIAS"
set_env_secret KEY_PASSWORD "$KEY_PASSWORD"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Back it up, then you are done"
say "GitHub now has a copy, but a repo is not a backup: if the secret is"
say "ever deleted or the repo goes, the key goes with it."
printf '\n'
step "Put $KEYSTORE_PATH in your password manager or an encrypted backup."
step "Store the store password, key password, and the alias \"$KEY_ALIAS\" beside it."
printf '\n'
confirm "Backed up?" || warn "do it before you publish the first release"

finish
say "From here on, releases are automatic:"
step "Merge conventional commits to main; release-please keeps a release PR open."
step "Merge that PR: it tags, publishes, and CI attaches the signed APK."
step "Users install from the GitHub release, or track the repo in Obtainium."
printf '\n'
